# Generated by Django 4.0.6 on 2022-07-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='medicine_images'),
        ),
    ]
