# Generated by Django 4.0.6 on 2022-07-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_medicinemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_image/'),
        ),
    ]
