# Generated by Django 4.0.6 on 2022-07-11 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0004_alter_medicinemodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('medicineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='App_main.medicinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('order_id', models.CharField(max_length=100)),
                ('ordered', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_manager', to='App_main.cartmanagermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
