# Generated by Django 4.0.6 on 2022-07-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0006_alter_cartmodel_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='medicineItem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='App_main.medicinemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CartManagerModel',
        ),
    ]
