# Generated by Django 4.0.6 on 2022-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_info',
            field=models.TextField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='selected_delivery_address',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
