# Generated by Django 4.0.6 on 2022-07-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('house_address', models.TextField()),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Home Town', 'Home Town')], max_length=12)),
            ],
        ),
    ]
