# Generated by Django 4.0.6 on 2022-07-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0004_deliveryaddressmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='areamodel',
            name='division_id',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division', to='App_auth.citymodel'),
            preserve_default=False,
        ),
    ]
